import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>App</header>
        <div>
          <section>
          <nav>
                <ul>
                    <il>Carts</il>
                    <il>Products</il>
                    <il>New Cards</il>
                    <il>New Products</il>
                </ul>
            </nav>

          </section>

          <main>
            {children}

          </main>

        </div>
        <footer>Diana Juliana Carranza Fonseca- 55821502</footer>

      </body>
    </html>
  )
}
