import './globals.css'
import Link from 'next/link';
import { Inter } from 'next/font/google'
import styles from './page.module.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <header className={styles.header}>App</header>
        <div>
          <section>
          <nav>
                <ul>
                    <li> <Link href={'/'} className={styles.opcionMenu}>Carts</Link></li>
                    <li><Link href={'/infoproductos'} className={styles.opcionMenu}>Products</Link></li>
                    <li><Link href={'/nuevocarrito'} className={styles.opcionMenu}>New Carts</Link></li>
    
                    <li><Link href={'/nuevoproducto'} className={styles.opcionMenu}>New products</Link></li>
                    
                </ul>
            </nav>

          </section>

          <main>
            {children}

          </main>

        </div>
        <footer className={styles.footerPrincipal}>Diana Juliana Carranza Fonseca- 55821502</footer>

      </body>
    </html>
  )
}
